package org.netbeans.modules.trintejs.templates.mvc;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public final class CreateServerSideControllerVisualPanelActions extends JPanel {

    /**
     * Creates new form CreateServerSideControllerVisualPanelActions
     */
    public CreateServerSideControllerVisualPanelActions() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Controller Actions";
    }

    public JTable getActionsTable() {
        return ActionsTable;
    }

    public static int[] getSelectedRowsModelIndices(JTable table) {
        if (table == null) {
            throw new NullPointerException("table == null");
        }

        int[] selectedRowIndices = table.getSelectedRows();
        int countSelected = selectedRowIndices.length;

        for (int i = 0; i < countSelected; i++) {
            selectedRowIndices[i] = table.convertRowIndexToModel(selectedRowIndices[i]);
        }

        return selectedRowIndices;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RemoveActionButton = new javax.swing.JButton();
        AddActionButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ActionsTable = new javax.swing.JTable();

        org.openide.awt.Mnemonics.setLocalizedText(RemoveActionButton, org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelActions.class, "CreateServerSideControllerVisualPanelActions.RemoveActionButton.text")); // NOI18N
        RemoveActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(AddActionButton, org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelActions.class, "CreateServerSideControllerVisualPanelActions.AddActionButton.text")); // NOI18N
        AddActionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionButtonActionPerformed(evt);
            }
        });

        ActionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ActionsTable);
        ActionsTable.getColumnModel().getColumn(0).setResizable(false);
        ActionsTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelActions.class, "CreateServerSideControllerVisualPanelActions.ActionsTable.columnModel.title0")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AddActionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveActionButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveActionButton)
                    .addComponent(AddActionButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionButtonActionPerformed
        DefaultTableModel TableModel = (DefaultTableModel) ActionsTable.getModel();
        int count = TableModel.getRowCount();
        String rowName = "action_" + (count + 1);

        TableModel.addRow(new String[]{rowName});
    }//GEN-LAST:event_AddActionButtonActionPerformed

    private void RemoveActionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionButtonActionPerformed
        int[] selectedRowIndices = getSelectedRowsModelIndices(ActionsTable);
        DefaultTableModel tableModel = (DefaultTableModel) ActionsTable.getModel();
        int countRemoved = 0;

        for (int selectedRowIndex : selectedRowIndices) {
            int removeIndex = selectedRowIndex - countRemoved;
            tableModel.removeRow(removeIndex);
            countRemoved++;
        }
    }//GEN-LAST:event_RemoveActionButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ActionsTable;
    private javax.swing.JButton AddActionButton;
    private javax.swing.JButton RemoveActionButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
