package org.netbeans.modules.trintejs.templates.mvc;

import javax.swing.JPanel;

public final class CreateServerSideControllerVisualPanelName extends JPanel {

    static final String CONTROLLER_NAME = "Example";
    static final String NAMESPACE = "";

    /**
     * Creates new form CreateServerSideControllerVisualPanelName
     */
    public CreateServerSideControllerVisualPanelName() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Controller Name";
    }

    public String getControllerName() {
        return ControllerNameTextField.getText();
    }

    public String getNameSpace() {
        return NamespaceTextField.getText();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControllerNameLabel = new javax.swing.JLabel();
        ControllerNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NamespaceTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(ControllerNameLabel, org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.ControllerNameLabel.text")); // NOI18N

        ControllerNameTextField.setText(org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.ControllerNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.jLabel1.text")); // NOI18N

        NamespaceTextField.setText(org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.NamespaceTextField.text")); // NOI18N
        NamespaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamespaceTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(ControllerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ControllerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(NamespaceTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ControllerNameLabel)
                    .addComponent(ControllerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NamespaceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NamespaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamespaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamespaceTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ControllerNameLabel;
    private javax.swing.JTextField ControllerNameTextField;
    private javax.swing.JTextField NamespaceTextField;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
