package org.netbeans.modules.trintejs.templates.mvc;

import javax.swing.JPanel;

public final class CreateServerSideModelVisualPanelName extends JPanel {

    static final String MODEL_NAME = "Example";

    /**
     * Creates new form CreateServerSideModelVisualPanelName
     */
    public CreateServerSideModelVisualPanelName() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Model Name";
    }

    public String getModelName() {
        return ModelNameTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ModelNameTextField = new javax.swing.JTextField();
        ModelNameLabel = new javax.swing.JLabel();

        ModelNameTextField.setText(org.openide.util.NbBundle.getMessage(CreateServerSideModelVisualPanelName.class, "CreateServerSideModelVisualPanelName.ModelNameTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(ModelNameLabel, org.openide.util.NbBundle.getMessage(CreateServerSideModelVisualPanelName.class, "CreateServerSideModelVisualPanelName.ModelNameLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(ModelNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModelNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModelNameLabel))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ModelNameLabel;
    private javax.swing.JTextField ModelNameTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
