package org.netbeans.modules.trintejs.templates.mvc;

import javax.swing.JPanel;

public final class CreateServerSideControllerVisualPanelName extends JPanel {

    static final String CONTROLLER_NAME = "Example";

    /**
     * Creates new form CreateServerSideControllerVisualPanelName
     */
    public CreateServerSideControllerVisualPanelName() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Controller Name";
    }

    public String getControllerName() {
        return ControllerNameTextField.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ControllerNameLabel = new javax.swing.JLabel();
        ControllerNameTextField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(ControllerNameLabel, org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.ControllerNameLabel.text")); // NOI18N

        ControllerNameTextField.setText(org.openide.util.NbBundle.getMessage(CreateServerSideControllerVisualPanelName.class, "CreateServerSideControllerVisualPanelName.ControllerNameTextField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ControllerNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ControllerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ControllerNameLabel)
                    .addComponent(ControllerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ControllerNameLabel;
    private javax.swing.JTextField ControllerNameTextField;
    // End of variables declaration//GEN-END:variables
}
