package org.netbeans.modules.trintejs.ui.wizards;

import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.netbeans.modules.trintejs.ui.FieldsTypes;

public final class CreateModelFieldsVisual extends JPanel {

    /**
     * Creates new form CreateModelFieldsVisual
     */
    public CreateModelFieldsVisual() {
        initComponents();
        TableColumn typeColumn = FieldsTable.getColumnModel().getColumn(1);
        JComboBox<String> comboBox = new JComboBox<String>();

        FieldsTypes[] fieldsTypes = FieldsTypes.values();
        for (int i = 0; i < fieldsTypes.length; i++) {
            String fieldsType = fieldsTypes[i].toString();
            comboBox.addItem(fieldsType);
        }

        typeColumn.setCellEditor(new DefaultCellEditor(comboBox));
    }

    @Override
    public String getName() {
        return "Model fields";
    }

    public JTable getFieldsTable() {
        return FieldsTable;
    }

    public static int[] getSelectedRowsModelIndices(JTable table) {
        if (table == null) {
            throw new NullPointerException("table == null");
        }

        int[] selectedRowIndices = table.getSelectedRows();
        int countSelected = selectedRowIndices.length;

        for (int i = 0; i < countSelected; i++) {
            selectedRowIndices[i] = table.convertRowIndexToModel(selectedRowIndices[i]);
        }

        return selectedRowIndices;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FieldsTable = new javax.swing.JTable();
        AddFieldButton = new javax.swing.JButton();
        RemoveRowButton = new javax.swing.JButton();

        FieldsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Field Name", "Field Type", "Default value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FieldsTable);
        FieldsTable.getColumnModel().getColumn(0).setResizable(false);
        FieldsTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(CreateModelFieldsVisual.class, "CreateModelFieldsVisual.FieldsTable.columnModel.title0")); // NOI18N
        FieldsTable.getColumnModel().getColumn(1).setResizable(false);
        FieldsTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(CreateModelFieldsVisual.class, "CreateModelFieldsVisual.FieldsTable.columnModel.title1")); // NOI18N
        FieldsTable.getColumnModel().getColumn(2).setResizable(false);
        FieldsTable.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(CreateModelFieldsVisual.class, "CreateModelFieldsVisual.FieldsTable.columnModel.title2_1")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(AddFieldButton, org.openide.util.NbBundle.getMessage(CreateModelFieldsVisual.class, "CreateModelFieldsVisual.AddFieldButton.text")); // NOI18N
        AddFieldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFieldButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(RemoveRowButton, org.openide.util.NbBundle.getMessage(CreateModelFieldsVisual.class, "CreateModelFieldsVisual.RemoveRowButton.text")); // NOI18N
        RemoveRowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveRowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddFieldButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveRowButton)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFieldButton)
                    .addComponent(RemoveRowButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddFieldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFieldButtonActionPerformed
        DefaultTableModel TableModel = (DefaultTableModel) FieldsTable.getModel();
        TableModel.addRow(new String[]{
                    "name", "String", null
                });
    }//GEN-LAST:event_AddFieldButtonActionPerformed

    private void RemoveRowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveRowButtonActionPerformed
        int[] selectedRowIndices = getSelectedRowsModelIndices(FieldsTable);
        DefaultTableModel tableModel = (DefaultTableModel) FieldsTable.getModel();
        int countRemoved = 0;

        for (int selectedRowIndex : selectedRowIndices) {
            int removeIndex = selectedRowIndex - countRemoved;
            tableModel.removeRow(removeIndex);
            countRemoved++;
        }
    }//GEN-LAST:event_RemoveRowButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFieldButton;
    private javax.swing.JTable FieldsTable;
    private javax.swing.JButton RemoveRowButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}